publish_to: none
name: app
description: A new Flutter project.

version: 1.0.13+47

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Vertical Mobi
  # vertical_ui_lib:
  #   path: /Users/marceloreis/Mobile/Vertical/libs/flutter/vertical_ui_lib
    # git:
    #   url: https://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@github.com/Vertical-Mobi/vertical-flutter-ui-lib.git
    #   ref: main


  # Google
  firebase_core: ^2.16.0
  firebase_remote_config: ^4.2.6
  firebase_analytics: ^10.5.0
  firebase_crashlytics: ^3.3.6
  firebase_messaging: ^14.6.8
  firebase_in_app_messaging: ^0.7.3+6

  # App System
  intl: ^0.18.1
  dio: ^5.3.3
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  flutter_localization: ^0.1.14
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  url_launcher: ^6.1.14
  flutter_udid: ^2.0.1
  logger: ^2.0.2+1
  flutter_secure_storage: ^9.0.0
  rate_my_app: ^2.0.0  
  flutter_fgbg: ^0.3.0
  
  # Layout

  # Fonts/Texts/Forms
  auto_size_text: ^3.0.0
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  currency_text_input_formatter: ^2.1.10
  flutter_masked_text2: ^0.9.1
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.5
  pin_code_fields: ^8.0.1
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.jpg"
flutter:
  generate: true
  uses-material-design: true

  assets:
    # Logos
    - assets/img/launch-screen.png

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-MediumItalic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 700

